### ISSUE TITLE
Change SSL Curl options

### ISSUE THREAD

**Issue by Juangb92** [akamai/AkamaiOPEN-edgegrid-php-client#22] opened 2016-02-23 17:17 UTC
Hi!
I'm working with Akamai, but I have a SSL issue with the requests. Normally when doing cURL requests I need to set CURLOPT_SSL_VERIFYPEER to false. My code looks like this: 

``` php
$client = new Akamai\Open\EdgeGrid\Client([     
        'base_uri' => "https://".$host
    ]);
    $client->setAuth($client_token, $client_secret, $access_token);
    $response = $client->get($options);
```

And I get the following error message:
`Fatal error:  Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in phar://....../akamai-open-edgegrid-client-0.4.3.phar/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187`

I noticed that this comes from CurlFactory from your Guzzle library, so I checked the project and saw the possibility to do something like this:

`$res = $this->client->request('GET', 'https://host', [
        'curl' => [
            CURLOPT_SSL_VERIFYPEER => false
        ],
    ]);` 

Is setting CURL options like this possible to do with Akamai-Open?
Or how can I go around this?

Thank you very much for your help! :)

Kind regards,
Juan

**Comment by dshafik** [comment] 2016-02-23 17:46
@Juangb92 setting curl settings with the `\Akamai\Open\Edgegrid\Client` should be identical to doing it directly with guzzle, as you showed.

You can actually either use the `request` method as you have:

``` php
$client->request('GET', 'https://host', [
    'curl' => [ CURLOPT_SSL_VERIFYPEER => false ]
]);
```

Or use the `get` method:

``` php
$client->get('https://host', [
    'curl' => [ CURLOPT_SSL_VERIFYPEER => false ]
]);
```

Please try and report back if you have further issues!

**Comment by dshafik** [comment] 2016-03-10 22:49
@Juangb92 did this solution work for you? I'd like to close this issue if so.

**Comment by Juangb92** [comment] 2016-03-11 09:25
Hi! Yes!!
Sorry for not replying right away, thank you very much, it was exactly what I was looking for.
Nice library by the way!
Cheers!

**Comment by dshafik** [comment] 2016-03-11 10:23
@Juangb92 thanks! Glad it helped!

**Closed as completed by dshafik** 2016-03-11 10:23 UTC

**Comment by ElijahLynn** [comment] 2016-03-22 18:19
@dshafik We just started getting this precise error # today via Guzzle and the Edgegrid PHP library. Although my error just says `error 60: SSL Certificate Problem, verify that the CA cert is OK`. It is confusing because it was working fine up until now. 

Is this something that is caused by the Akamai certificate?
